// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace TwoWayViewModel
{
    [Microsoft.UI.Xaml.Data.Bindable]
    runtimeclass CheckBoxViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        CheckBoxViewModel();
        Int32 MyProperty;
        Boolean IsChecked;
        String Text{ get; };
        void UpdateText();
    }
}
