// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace TwoWayViewModel
{
    [default_interface]
    runtimeclass CheckBoxViewModel 
    {
        CheckBoxViewModel();
        Int32 MyProperty;
    }
}
