// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "CheckBoxViewModel.idl";

namespace TwoWayViewModel
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
        CheckBoxViewModel ViewModel{ get; };
    }
}
